### ISSUE TITLE
是否有完整的使用文档？

### ISSUE THREAD

**Issue by yunbaozhou** [SkyAPM/SkyAPM-dotnet#287]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [1 ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and .NET Runtime?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by ElderJames** [comment]
Thank you for contacting us.
SkyApm-dotnet is simple enough as the agent side of SkyWalking, so that you can setup it just by reading the [README](https://github.com/SkyAPM/SkyAPM-dotnet/blob/master/README.md).
To learn more about SkyWalking, you need to read the [official documentation](https://github.com/apache/skywalking/blob/master/docs/README.md).
